stages:
  - build
  - test
  - upload-docker

# Build the frontend
frontend-build:
  stage: build
  image: node:20-alpine
  tags:
    - docker
  script:
    - cd client
    - npm install
    - npm run build
  artifacts:
    paths:
      - client/dist

stress-test-mqtt:
  stage: test
  image: ubuntu:latest
  tags:
    - docker
  before_script:
    - apt-get update && apt-get install -y curl git #Install curl
    - curl -LO https://go.dev/dl/go1.23.4.linux-amd64.tar.gz #Install go
    - tar -C /usr/local -xzf go1.23.4.linux-amd64.tar.gz #open file
    - export PATH=$PATH:/usr/local/go/bin
    - go version
    - go install github.com/krylovsk/mqtt-benchmark@main # Install stress-test tool
    - export PATH=$PATH:$(go env GOPATH)/bin
  script:
    - chmod +x mqtt_test.sh #execute stress-test bash
    - ./mqtt_test.sh #start bash

# Builds the authentication service
Authentication-service-build:
  stage: build
  image: maven:3.9.4-eclipse-temurin-17
  tags:
    - docker
  script:
    - cd services/AuthenticationService
    - echo "Building Authentication Service..."
    - mvn clean package
  artifacts:
    paths:
      - services/AuthenticationService/target/

# Builds the clinic service
Clinic-service-build:
  stage: build
  image: maven:3.9.4-eclipse-temurin-17
  tags:
    - docker
  script:
    - cd services/ClinicService
    - echo "Building Clinic Service..."
    - mvn clean package
  artifacts:
    paths:
      - services/ClinicService/target/
      
# Builds the notification service
Notification-service-build:
  stage: build
  image: maven:3.9.4-eclipse-temurin-17
  tags:
    - docker
  script:
    - cd services/NotificationService
    - echo "Building Notification Service..."
    - mvn clean package
  artifacts:
    paths:
      - services/NotificationService/target/

# Builds the schedule service
Schedule-service-build:
  stage: build
  image: maven:3.9.4-eclipse-temurin-17
  tags:
    - docker
  script:
    - cd services/ScheduleService
    - echo "Building Schedule Service..."
    - mvn clean package
  artifacts:
    paths:
      - services/ScheduleService/target/

# Builds and pushes the AuthenticationService docker image
Authentication-service-docker:
  stage: upload-docker
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin registry.git.chalmers.se
  dependencies:
    - Authentication-service-build
  script:
    - cd services/AuthenticationService
    - docker build -t registry.git.chalmers.se/courses/dit355/2024/student_teams/dit356_2024_20/dit-356-project-group-20/authentication-service .
    - docker push registry.git.chalmers.se/courses/dit355/2024/student_teams/dit356_2024_20/dit-356-project-group-20/authentication-service
  tags:
    - docker-build

# Builds and pushes the ClinicService docker image
Clinic-service-docker:
  stage: upload-docker
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin registry.git.chalmers.se
  dependencies:
    - Clinic-service-build
  script:
    - cd services/ClinicService
    - docker build -t registry.git.chalmers.se/courses/dit355/2024/student_teams/dit356_2024_20/dit-356-project-group-20/clinic-service .
    - docker push registry.git.chalmers.se/courses/dit355/2024/student_teams/dit356_2024_20/dit-356-project-group-20/clinic-service
  tags:
    - docker-build

# Builds and pushes the scheduleService docker image
Schedule-service-docker:
  stage: upload-docker
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin registry.git.chalmers.se
  dependencies:
    - Schedule-service-build
  script:
    - cd services/ScheduleService
    - docker build -t registry.git.chalmers.se/courses/dit355/2024/student_teams/dit356_2024_20/dit-356-project-group-20/schedule-service .
    - docker push registry.git.chalmers.se/courses/dit355/2024/student_teams/dit356_2024_20/dit-356-project-group-20/schedule-service
  tags:
    - docker-build

# Builds and pushes the notificationService docker image
Notification-service-docker:
  stage: upload-docker
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin registry.git.chalmers.se
  dependencies:
    - Notification-service-build
  script:
    - cd services/NotificationService
    - docker build -t registry.git.chalmers.se/courses/dit355/2024/student_teams/dit356_2024_20/dit-356-project-group-20/notification-service .
    - docker push registry.git.chalmers.se/courses/dit355/2024/student_teams/dit356_2024_20/dit-356-project-group-20/notification-service
  tags:
    - docker-build