stages:
  - build

# Build the Vue frontend
frontend-build:
  stage: build
  image: node:16
  script:
    - cd client
    - npm install
    - npm run build
  artifacts:
    paths:
      - client/dist
  only:
    - main

# Build the Express backend
backend-build:
  stage: build
  image: node:16
  script:
    - cd server
    - npm install
  artifacts:
    paths:
      - server