spring.data.mongodb.uri=mongodb+srv://vaibhavpuram05:DIT356GROUP20@patientdb1.5oq2p.mongodb.net/
spring.data.mongodb.database=LoggingDB
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ToothRepair356@gmail.com
spring.mail.password=echl gfcp zuwf mkxw
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
